# Generated by Django 4.0.8 on 2022-12-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0002_order_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='type',
        ),
    ]
